### ISSUE TITLE
mining drill mk3 can dig in protected areas

### ISSUE THREAD

**Issue by Desour** [HybridDog/technic_extras#2]
Schrieb jedenfalls @Lejo1 [hier](https://forum.minetest.net/viewtopic.php?f=21&t=17959).

**Comment by Lejo1** [comment]
But only if you hold the right mouse button!

**Comment by HybridDog** [comment]
can't reproduce

**Comment by Lejo1** [comment]
Sorry, maybe I had an older version. I don't know now it works. :)
